/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Setup_1.java
 *
 * Created on Jun 14, 2016, 2:00:31 PM
 */
package com.SetupView;

/**
 *
 * @author brianmadmaxsy
 */
public class Setup_1 extends javax.swing.JFrame {

    /** Creates new form Setup_1 */
    public Setup_1() {
        initComponents();
        this.setLocationRelativeTo(null); //This centralizes the Jframe. 
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main_Container = new javax.swing.JPanel();
        lock_icon = new javax.swing.JLabel();
        starter = new javax.swing.JButton();
        copyright = new javax.swing.JLabel();
        Main_Container_Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Main_Container.setLayout(null);

        lock_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/SetupImages/LOCK (light blue background).jpg"))); // NOI18N
        lock_icon.setText("jLabel1");
        lock_icon.setAlignmentY(0.0F);
        Main_Container.add(lock_icon);
        lock_icon.setBounds(110, 70, 160, 60);

        starter.setText("Let's Start!");
        starter.setAlignmentY(0.0F);
        starter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                starterActionPerformed(evt);
            }
        });
        Main_Container.add(starter);
        starter.setBounds(150, 160, 100, 30);

        copyright.setForeground(new java.awt.Color(-12566464,true));
        copyright.setText("All Rights Reserved WADDC");
        Main_Container.add(copyright);
        copyright.setBounds(130, 270, 170, 14);

        Main_Container_Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/SetupImages/light-blue-background.jpg"))); // NOI18N
        Main_Container.add(Main_Container_Background);
        Main_Container_Background.setBounds(0, 0, 400, 290);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main_Container, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main_Container, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void starterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_starterActionPerformed
        new Setup_2().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_starterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Setup_1().setVisible(true);
                //new Setup_1().setSize(500, 500);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Main_Container;
    private javax.swing.JLabel Main_Container_Background;
    private javax.swing.JLabel copyright;
    private javax.swing.JLabel lock_icon;
    private javax.swing.JButton starter;
    // End of variables declaration//GEN-END:variables
}
