/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Setup_1.java
 *
 * Created on Jun 14, 2016, 2:00:31 PM
 */
package com.SetupView;

import java.util.ArrayList;
import com.SetupClass.*;
/**
 *
 * @author brianmadmaxsy
 */
public class Setup_2 extends javax.swing.JFrame {

    /** Creates new form Setup_1 */
    public Setup_2() {
        initComponents();
        this.setLocationRelativeTo(null); //This centralizes the Jframe. 
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main_Container = new javax.swing.JPanel();
        lock_icon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfusername = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        login = new javax.swing.JButton();
        register = new javax.swing.JLabel();
        copyright = new javax.swing.JLabel();
        popup_message = new javax.swing.JLabel();
        Main_Container_Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Main_Container.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lock_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/SetupImages/LOCK (light blue background).jpg"))); // NOI18N
        lock_icon.setText("jLabel1");
        lock_icon.setAlignmentY(0.0F);
        Main_Container.add(lock_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 160, 60));

        jLabel1.setText("Username");
        Main_Container.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 60, -1));

        jLabel2.setText("Password");
        Main_Container.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 60, -1));
        Main_Container.add(tfusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 120, 20));
        Main_Container.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 120, -1));

        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        Main_Container.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 80, 30));

        register.setFont(new java.awt.Font("Dialog", 0, 14));
        register.setForeground(new java.awt.Color(0, 153, 0));
        register.setText("Register!");
        register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                registerMousePressed(evt);
            }
        });
        Main_Container.add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 90, 30));

        copyright.setForeground(new java.awt.Color(-12566464,true));
        copyright.setText("All Rights Reserved WADDC");
        Main_Container.add(copyright, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 200, -1));

        popup_message.setForeground(new java.awt.Color(-65536,true));
        Main_Container.add(popup_message, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 220, 10));

        Main_Container_Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/SetupImages/light-blue-background.jpg"))); // NOI18N
        Main_Container.add(Main_Container_Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 290));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main_Container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main_Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        
        setupWebService ws = new setupWebService();
        Session sess = new Session();

        String hashedPassword = "";
        ArrayList<String> array = new ArrayList<String>();
        String input_username=tfusername.getText();
        String input_password=password.getText();

        hashedPassword = md5hashing.getMD5(input_password);

        array=ws.login_webservice(input_username, input_password);

        String status=array.get(0);
        String message=array.get(1);
        String username=array.get(2);
            //String accounttype=array.get(3);

            //System.out.println("Status: "+status+" || Message: "+message+" || Username: "+username+" || Account: "+accounttype);
        if("success".equals(status))
        {
            String loc="C://ProgramData/lock_setup_temp.txt";
            sess.setHiddenData(username,loc);
            new Setup_3().setVisible(true);
            this.dispose();
        }
        else
        {
            popup_message.setText("Account not found!");
        }
        
        
        
         
    }//GEN-LAST:event_loginActionPerformed

    private void registerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMousePressed
        registerUI register = new registerUI();
        register.setVisible(true);
        
    }//GEN-LAST:event_registerMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new Setup_2().setVisible(true);
                new Setup_2().setSize(500, 500);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Main_Container;
    private javax.swing.JLabel Main_Container_Background;
    private javax.swing.JLabel copyright;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lock_icon;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel popup_message;
    private javax.swing.JLabel register;
    private javax.swing.JTextField tfusername;
    // End of variables declaration//GEN-END:variables
}
