/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Setup_3.java
 *
 * Created on Jun 16, 2016, 2:13:15 PM
 */
package com.SetupView;

/**
 *
 * @author brianmadmaxsy
 */

import java.util.Enumeration;
import com.jacob.activeX.ActiveXComponent;
import com.jacob.com.ComThread;
import com.jacob.com.EnumVariant;
import com.jacob.com.Variant;
import com.SetupClass.*;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class Setup_3 extends javax.swing.JFrame {

    /** Creates new form Setup_3 */
    DefaultTableModel table;
    public Setup_3() {
        initComponents();
        this.setLocationRelativeTo(null); //This centralizes the Jframe. 
        
        table=(DefaultTableModel)accounts.getModel();
        //get the list of windows local user 
        /*
        String s="";
        ComThread.InitMTA();
        try 
        {
            ActiveXComponent wmi = new ActiveXComponent("winmgmts:\\\\.");
            Variant instances = wmi.invoke("InstancesOf", "Win32_UserAccount");
            Enumeration<Variant> en = new EnumVariant(instances.getDispatch());
            
           
            
            while (en.hasMoreElements())
            {
                ActiveXComponent bb = new ActiveXComponent(en.nextElement().getDispatch());
                //System.out.println(bb.getPropertyAsString("PartComponent"));
                s=bb.getPropertyAsString("Name");
                //System.out.println(s);
                win_acct.addItem(s);
                //System.out.println(bb.getPropertyAsComponent("name"));
            }
            
             
        } 
        finally {
            ComThread.Release();
        }
        
        //end of get list of windows local user
        */
        
        //Start of getting the list of child account under parent
        
        
        
       
        getLocalUsers getloc = new getLocalUsers();
        ArrayList<String> names = new ArrayList<String>();
        
        names=getloc.getLocalUsers();
        
        
        for(int x=0; x<getloc.count;x++)
        {
            
            win_acct.addItem(names.get(x));
        }
        
        
        
        
        Session sess = new Session();
        String parentusername="";
        
        parentusername=sess.seekHiddenData("C://ProgramData/lock_setup_temp.txt");
        sess.setHiddenData("","C://ProgramData/lock_setup_temp.txt"); //reset to null
        
        setupWebService webservice = new setupWebService();
        webservice.getchildusers(parentusername);
        Children[] users;
        
        users=webservice.enums;
        
        for(int i=0;i<users.length;i++)
        {
            //System.out.println(users[i].getUsername());
            child_acct.addItem(users[i].getUsername());
        }
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        lock_icon = new javax.swing.JLabel();
        Content1_container = new javax.swing.JPanel();
        lbl_title = new javax.swing.JLabel();
        lbl_definition = new javax.swing.JLabel();
        lbl_winAcct = new javax.swing.JLabel();
        win_acct = new javax.swing.JComboBox();
        lbl_childAcct = new javax.swing.JLabel();
        child_acct = new javax.swing.JComboBox();
        associate_button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        remove = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        copyright = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        accounts = new javax.swing.JTable();
        Main_Container_Background = new javax.swing.JLabel();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lock_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/SetupImages/LOCK (light blue background).jpg"))); // NOI18N
        lock_icon.setText("jLabel1");
        lock_icon.setAlignmentY(0.0F);
        getContentPane().add(lock_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 160, 60));

        lbl_title.setFont(new java.awt.Font("Dialog", 1, 14));
        lbl_title.setText("Associate Accounts");

        lbl_definition.setText("Associate a windows user account to a child");

        lbl_winAcct.setText("Windows Account");

        lbl_childAcct.setText("Child Account");

        associate_button.setText("Associate");
        associate_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                associate_buttonActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        remove.setText("Remove");
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Content1_containerLayout = new javax.swing.GroupLayout(Content1_container);
        Content1_container.setLayout(Content1_containerLayout);
        Content1_containerLayout.setHorizontalGroup(
            Content1_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Content1_containerLayout.createSequentialGroup()
                .addGroup(Content1_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Content1_containerLayout.createSequentialGroup()
                        .addGap(482, 482, 482)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Content1_containerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Content1_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_title)
                            .addGroup(Content1_containerLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(Content1_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_definition)
                                    .addGroup(Content1_containerLayout.createSequentialGroup()
                                        .addGroup(Content1_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(associate_button)
                                            .addGroup(Content1_containerLayout.createSequentialGroup()
                                                .addComponent(lbl_winAcct)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(win_acct, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(Content1_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(Content1_containerLayout.createSequentialGroup()
                                                .addComponent(child_acct, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lbl_childAcct))
                                            .addComponent(remove))))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Content1_containerLayout.setVerticalGroup(
            Content1_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Content1_containerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_definition)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Content1_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_winAcct)
                    .addComponent(win_acct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(child_acct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_childAcct))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Content1_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(associate_button)
                    .addComponent(remove))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(Content1_container, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 490, 140));

        submit.setText("Install");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 70, -1));

        Cancel.setText("Cancel");
        getContentPane().add(Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, -1, -1));

        copyright.setForeground(new java.awt.Color(-12566464,true));
        copyright.setText("All Rights Reserved WADDC");
        getContentPane().add(copyright, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 170, -1));

        accounts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Window's Account", "Child Account"
            }
        ));
        accounts.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane3.setViewportView(accounts);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 490, 90));

        Main_Container_Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/SetupImages/light-blue-background.jpg"))); // NOI18N
        getContentPane().add(Main_Container_Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void associate_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_associate_buttonActionPerformed
        //add item to table
        //int count=0;
        table.insertRow(table.getRowCount(), new Object[]{table.getRowCount()+1,win_acct.getSelectedItem(),child_acct.getSelectedItem()});
    }//GEN-LAST:event_associate_buttonActionPerformed

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
        //Remove a table row
        table.removeRow(accounts.getSelectedRow());
    }//GEN-LAST:event_removeActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        ArrayList<String> child_data;
        Session sess = new Session();
        setupWebService s = new setupWebService();
        if(table.getRowCount()>0)
        {
            copyData cd = new copyData();
            int count=table.getRowCount();
            for(int i=0;i<count;i++)
            {
               int o=0;
               //System.out.println(" ID: "+table.getValueAt(i, o)+" Windows Account: "+table.getValueAt(i, o+1)+" Lock Account: "+table.getValueAt(i, o+2));
               try
               {
                    child_data=s.getchild(""+table.getValueAt(i,o+2)); //get child data using username parameter
                    String child_userid=child_data.get(0);
                    sess.setHiddenData(child_userid, "C:\\Users"+"\\"+table.getValueAt(i,o+1)+"\\AppData\\Local\\user.txt");
                
               }
               catch(Exception ex)
               {
                  JOptionPane.showMessageDialog(null,ex); 
               }
               String lockfile = System.getProperty("user.dir")+"/Lock/app";
               String toFolder = "C:\\Users"+"/"+table.getValueAt(i,o+1);
               File srcFolder = new File(lockfile);
               File destFolder = new File(toFolder);
               
               //String shortcut = System.getProperty("user.dir")+"/Lock/shortcut";
               String startup = "C:\\Users\\"+table.getValueAt(i,o+1)+"\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Startup";
               
               //File srcStartup = new File(shortcut);
               //File destStartup = new File(startup);
               try
               {
                  cd.copyFolder(srcFolder, destFolder); // for the lock app
                  //cd.copyFolder(srcStartup, destStartup);
                  //sess.setHiddenData(""+table.getValueAt(i,o+2), "C:\\Users"+"\\"+table.getValueAt(i,o+1)+"\\AppData\\Local\\user.txt");
                  ProcessBuilder pb = new ProcessBuilder("cmd", "/c", "start",System.getProperty("user.dir")+"\\shortcutgen.bat",
                    "C:\\Users"+"\\"+table.getValueAt(i,o+1)+"\\LockProject\\dist\\LockProject.jar", startup+"\\Lock.lnk");
                  pb.start();
               }
               catch(IOException io)
               {
                  JOptionPane.showMessageDialog(null,io); 
               }
            
            }
        }
        else{
            JOptionPane.showMessageDialog(null,"Table is Empty");
        }
    }//GEN-LAST:event_submitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new Setup_3().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JPanel Content1_container;
    private javax.swing.JLabel Main_Container_Background;
    private javax.swing.JTable accounts;
    private javax.swing.JButton associate_button;
    private javax.swing.JComboBox child_acct;
    private javax.swing.JLabel copyright;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lbl_childAcct;
    private javax.swing.JLabel lbl_definition;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JLabel lbl_winAcct;
    private javax.swing.JLabel lock_icon;
    private javax.swing.JButton remove;
    private javax.swing.JButton submit;
    private javax.swing.JComboBox win_acct;
    // End of variables declaration//GEN-END:variables
}
