/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LockUI.java
 *
 * Created on Sep 30, 2015, 1:11:40 PM
 */
package com.LockView;

import com.LockClasses.*;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.*;
import javax.swing.*;


/**
 *
 * @author brianmadmaxsy
 */


public class LockUI extends javax.swing.JFrame {

    
    public String ip;
    public String pic = "/LockPackag/Parental-Control-Bar-Logo.png";

    /** Creates new form LockUI */
    public LockUI() {
        initComponents();
        this.setLocationRelativeTo(null); //This centralizes the Jframe. 
        
        Date d1 = new Date();
        SimpleDateFormat df = new SimpleDateFormat("MM/dd/YYYY HH:mm a");
        String Date = df.format(d1);
        
        getInfo gi = new getInfo(); //For the get IP address
        gi.getIP();

        NTSystem nts = new NTSystem();
        nts.auth_credentials();
        
        //Displays value to their respective output(textboxes located at tab named Unit)
        ip_output.setText(gi.ipAddress);
        domain_output.setText(nts.domain);
        domain_sid_output.setText(nts.domainsid);
        os_output.setText(nts.OS);
        username_output.setText(nts.name);
        usid_output.setText(nts.usersid);
        date_output.setText(Date);
        
        //Get the hidden userid
        
        
        Hidden hidden = new Hidden();
        
        lock_webservice lws = new lock_webservice();
        String win_username=nts.name;
        String userid = hidden.seekHiddenData("C:\\Users\\"+win_username+"\\AppData\\Local\\user.txt");
        
        
        //Get child user's firstname, lastname, username using the userid hidden
        String firstname,lastname, username, childid, computerid, parentusername, child_status;
        ArrayList<String> userdata;
        userdata=lws.getchild_usingUserId(userid);
        firstname=userdata.get(0);
        lastname=userdata.get(1);
        username=userdata.get(2);
        childid=userdata.get(3); 
        computerid=userdata.get(4);
        parentusername=userdata.get(5);
        child_status=userdata.get(6);
        
        if("disabled".equals(child_status) || "".equals(child_status))
        {
            child_status="disabled";
        }
        display_user_name.setText(firstname+" "+lastname+"!");
        output_parent.setText(parentusername);
        protection_status.setText("Protection status "+child_status);
        /*
        //Blocking starts here
        Blocker block = new Blocker();
        ResultSet result;
        result=db.getBlocklist(childid);
        block.enablePermission(); //enables the permissions in the host file
        
        try
        {
            while(result.next())
            {
                block.blocksite(result.getString("website"));
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        
        block.disablePermission(); //disable the permissions in the host file
        */
        //System.out.println(childid);
        //output to swing
        
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        Tabs1 = new javax.swing.JTabbedPane();
        HomePanel = new javax.swing.JPanel();
        HomeImage1 = new javax.swing.JLabel();
        HomePanelContent = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        frequentlyused = new javax.swing.JLabel();
        systeminfo = new javax.swing.JLabel();
        userinfo = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        protection_status = new javax.swing.JLabel();
        output_parent = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        display_user_name = new javax.swing.JLabel();
        signout = new javax.swing.JLabel();
        UnitPanel = new javax.swing.JPanel();
        UnitPanelContainer = new javax.swing.JPanel();
        ComputerInfoContainer = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ip_output = new javax.swing.JTextField();
        domain_sid_output = new javax.swing.JTextField();
        os_output = new javax.swing.JTextField();
        domain_output = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        username_output = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        usid_output = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        date_output = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(-1,true));

        container.setBackground(new java.awt.Color(-1,true));
        container.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HomePanel.setBackground(new java.awt.Color(-1,true));

        HomeImage1.setBackground(new java.awt.Color(-1,true));
        HomeImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/LockImages/Parental-Control-Bar-Logo.png"))); // NOI18N

        HomePanelContent.setBackground(new java.awt.Color(-1,true));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/LockImages/parenticon.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        frequentlyused.setFont(new java.awt.Font("Serif", 1, 14));
        frequentlyused.setText("Frequently Used");

        systeminfo.setForeground(new java.awt.Color(-16776961,true));
        systeminfo.setText("System Unit Info");
        systeminfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                systeminfoMousePressed(evt);
            }
        });

        userinfo.setForeground(new java.awt.Color(-16776961,true));
        userinfo.setText("User Logs");
        userinfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userinfoMousePressed(evt);
            }
        });

        jLabel13.setForeground(new java.awt.Color(-16776961,true));
        jLabel13.setText("Help and Assistance");

        jLabel14.setFont(new java.awt.Font("Serif", 1, 14));
        jLabel14.setText("Information");

        jLabel15.setText("Parent In-charge");

        jLabel16.setText("Lock application running... ");

        output_parent.setFont(new java.awt.Font("Dialog", 1, 12));
        output_parent.setForeground(new java.awt.Color(-16711936,true));

        javax.swing.GroupLayout HomePanelContentLayout = new javax.swing.GroupLayout(HomePanelContent);
        HomePanelContent.setLayout(HomePanelContentLayout);
        HomePanelContentLayout.setHorizontalGroup(
            HomePanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelContentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(HomePanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(HomePanelContentLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(frequentlyused))
                    .addGroup(HomePanelContentLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(HomePanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(systeminfo)
                            .addComponent(userinfo)
                            .addComponent(jLabel13))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(HomePanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14)
                    .addGroup(HomePanelContentLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(HomePanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(protection_status, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(HomePanelContentLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(output_parent, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        HomePanelContentLayout.setVerticalGroup(
            HomePanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelContentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(HomePanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(HomePanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, HomePanelContentLayout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(HomePanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel15)
                                .addComponent(output_parent, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel16)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(protection_status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, HomePanelContentLayout.createSequentialGroup()
                            .addComponent(frequentlyused)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(systeminfo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(userinfo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel13))))
                .addContainerGap())
        );

        jLabel11.setFont(new java.awt.Font("Serif", 1, 14));
        jLabel11.setText("Welcome");

        display_user_name.setFont(new java.awt.Font("Serif", 0, 14));

        signout.setFont(new java.awt.Font("Dialog", 0, 14));
        signout.setForeground(new java.awt.Color(-16776961,true));
        signout.setText("Sign Out");
        signout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                signoutMousePressed(evt);
            }
        });

        javax.swing.GroupLayout HomePanelLayout = new javax.swing.GroupLayout(HomePanel);
        HomePanel.setLayout(HomePanelLayout);
        HomePanelLayout.setHorizontalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(HomePanelLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(display_user_name, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(signout))
                    .addComponent(HomeImage1))
                .addContainerGap())
            .addComponent(HomePanelContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        HomePanelLayout.setVerticalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(display_user_name, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(signout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(HomeImage1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HomePanelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Tabs1.addTab("Home", HomePanel);

        UnitPanelContainer.setBackground(new java.awt.Color(-1,true));
        UnitPanelContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ComputerInfoContainer.setBackground(new java.awt.Color(-1,true));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/LockImages/computer.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel5.setText("Domain SID");

        jLabel6.setText("IP Address");

        jLabel7.setText("Domain Name");

        jLabel8.setText("System OS");

        ip_output.setEditable(false);
        ip_output.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        domain_sid_output.setEditable(false);
        domain_sid_output.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        os_output.setEditable(false);
        os_output.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        domain_output.setEditable(false);
        domain_output.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel9.setText("User Name");

        username_output.setEditable(false);
        username_output.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel10.setText("User SID");

        usid_output.setEditable(false);
        usid_output.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/LockImages/user.png"))); // NOI18N

        javax.swing.GroupLayout ComputerInfoContainerLayout = new javax.swing.GroupLayout(ComputerInfoContainer);
        ComputerInfoContainer.setLayout(ComputerInfoContainerLayout);
        ComputerInfoContainerLayout.setHorizontalGroup(
            ComputerInfoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ComputerInfoContainerLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(ComputerInfoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, Short.MAX_VALUE))
                .addGroup(ComputerInfoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ComputerInfoContainerLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(ComputerInfoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(ComputerInfoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addGroup(ComputerInfoContainerLayout.createSequentialGroup()
                                    .addGap(13, 13, 13)
                                    .addComponent(jLabel6))
                                .addGroup(ComputerInfoContainerLayout.createSequentialGroup()
                                    .addGap(13, 13, 13)
                                    .addComponent(jLabel8)))
                            .addComponent(jLabel5))
                        .addGap(10, 10, 10)
                        .addGroup(ComputerInfoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ip_output, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                            .addComponent(os_output, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                            .addComponent(domain_output, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                            .addComponent(domain_sid_output, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)))
                    .addGroup(ComputerInfoContainerLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(ComputerInfoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(ComputerInfoContainerLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel10)))
                        .addGap(10, 10, 10)
                        .addGroup(ComputerInfoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(usid_output, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                            .addComponent(username_output, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE))))
                .addContainerGap())
        );
        ComputerInfoContainerLayout.setVerticalGroup(
            ComputerInfoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ComputerInfoContainerLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(ComputerInfoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ComputerInfoContainerLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel7)
                        .addGap(38, 38, 38)
                        .addGroup(ComputerInfoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(ip_output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(ComputerInfoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(os_output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ComputerInfoContainerLayout.createSequentialGroup()
                        .addComponent(domain_output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ComputerInfoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(domain_sid_output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addGap(25, 25, 25)
                .addGroup(ComputerInfoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ComputerInfoContainerLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel9)
                        .addGap(17, 17, 17)
                        .addGroup(ComputerInfoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(usid_output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ComputerInfoContainerLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(username_output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4)))
        );

        UnitPanelContainer.add(ComputerInfoContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 232));

        javax.swing.GroupLayout UnitPanelLayout = new javax.swing.GroupLayout(UnitPanel);
        UnitPanel.setLayout(UnitPanelLayout);
        UnitPanelLayout.setHorizontalGroup(
            UnitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UnitPanelContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
        );
        UnitPanelLayout.setVerticalGroup(
            UnitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UnitPanelContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Tabs1.addTab("System", UnitPanel);

        jPanel1.setBackground(new java.awt.Color(-1,true));

        jLabel18.setText("Date");

        date_output.setEditable(false);

        jLabel19.setFont(new java.awt.Font("Dialog", 0, 14));
        jLabel19.setText("User's Log");

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(date_output, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(date_output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        Tabs1.addTab("Log", jPanel1);

        container.add(Tabs1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 510, 260));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 12));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("All Rights Reserved WADDC Lock");
        container.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/LockImages/LOCK (white background).jpg"))); // NOI18N
        container.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 170, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void systeminfoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_systeminfoMousePressed
        //System Info
    }//GEN-LAST:event_systeminfoMousePressed

    private void userinfoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userinfoMousePressed
        //User Info
    }//GEN-LAST:event_userinfoMousePressed

    private void signoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signoutMousePressed
        Hidden hidden = new Hidden();
        Blocker block = new Blocker();
        NTSystem nts = new NTSystem();
        nts.auth_credentials();
        String win_username=nts.name;
        
        hidden.setHiddenData("","C:\\Users\\"+win_username+"\\AppData\\Local\\user.txt"); //Set the hidden file data to null
        
        block.enablePermission();
        block.resetHost();
        block.writeHost();
        block.disablePermission();
        new LoginUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_signoutMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            @Override
            public void run() {
               //Model db = new Model();
               /* 
               NTSystem nt = new NTSystem();
                nt.auth_credentials();
                
                Hidden hidden = new Hidden();
                
                String win_username=nt.name;
                String userid="";
                userid=hidden.seekHiddenData("C:\\Users\\"+win_username+"\\AppData\\Local\\user.txt");
                
                if(!"".equals(userid))
                {
                    String childid="",computerid="",parentusername="",child_status="",sid="";
                    ArrayList<String> child_data = new ArrayList<String>();
                    
                    child_data=ws.getchildinfo(userid);
                    childid=child_data.get(2); 
                    computerid=child_data.get(0);
                    sid=child_data.get(1);
                    if(nt.usersid.equals(sid))
                    {
                        if("".equals(hidden.seekUserid()))
                        {
                            //no log in activity
                            new LoginUI().setVisible(true); 
                        }
                        else
                        {
                            //Can log in

                            new LockUI().setVisible(true); 
                        }
                    }
                    else
                    {
                        new LoginUI().setVisible(true);
                    }
                }
                else{
                    new LoginUI().setVisible(true);
                }
                */
                
                new LockUI().setVisible(true); 
                    
                
            }
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ComputerInfoContainer;
    private javax.swing.JLabel HomeImage1;
    private javax.swing.JPanel HomePanel;
    private javax.swing.JPanel HomePanelContent;
    private javax.swing.JTabbedPane Tabs1;
    private javax.swing.JPanel UnitPanel;
    private javax.swing.JPanel UnitPanelContainer;
    private javax.swing.JPanel container;
    private javax.swing.JTextField date_output;
    private javax.swing.JLabel display_user_name;
    private javax.swing.JTextField domain_output;
    private javax.swing.JTextField domain_sid_output;
    private javax.swing.JLabel frequentlyused;
    private javax.swing.JTextField ip_output;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField os_output;
    private javax.swing.JLabel output_parent;
    private javax.swing.JLabel protection_status;
    private javax.swing.JLabel signout;
    private javax.swing.JLabel systeminfo;
    private javax.swing.JLabel userinfo;
    private javax.swing.JTextField username_output;
    private javax.swing.JTextField usid_output;
    // End of variables declaration//GEN-END:variables
}
