/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LoginUI.java
 *
 * Created on Jan 5, 2016, 11:04:36 AM
 */
package com.LockView;

import com.LockClasses.*;
import java.util.*;
import java.io.RandomAccessFile;
import java.io.EOFException;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author brianmadmaxsy
 */
public class LoginUI extends javax.swing.JFrame {

    /** Creates new form LoginUI */
    public LoginUI() {
        initComponents();
        
        //errormessage.setText("Account not found!");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ContainerPanel = new javax.swing.JPanel();
        LockLogo = new javax.swing.JLabel();
        ContentPanel = new javax.swing.JPanel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        loginbutton = new javax.swing.JButton();
        Username = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        rememberme = new javax.swing.JCheckBox();
        register = new javax.swing.JLabel();
        copyright = new javax.swing.JLabel();
        errormessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(-1,true));

        ContainerPanel.setBackground(new java.awt.Color(-1,true));

        LockLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/LockImages/LOCK (white background).jpg"))); // NOI18N
        LockLogo.setAlignmentY(0.0F);

        ContentPanel.setBackground(new java.awt.Color(-1,true));
        ContentPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        loginbutton.setText("Login");
        loginbutton.setAutoscrolls(true);
        loginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbuttonActionPerformed(evt);
            }
        });

        Username.setText("Username");

        Password.setText("Password");

        rememberme.setBackground(new java.awt.Color(-1,true));
        rememberme.setText("Remember Me?");
        rememberme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remembermeActionPerformed(evt);
            }
        });

        register.setForeground(new java.awt.Color(-16776961,true));
        register.setText("Register Now!");
        register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                registerMousePressed(evt);
            }
        });
        register.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                registerPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout ContentPanelLayout = new javax.swing.GroupLayout(ContentPanel);
        ContentPanel.setLayout(ContentPanelLayout);
        ContentPanelLayout.setHorizontalGroup(
            ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContentPanelLayout.createSequentialGroup()
                        .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Username)
                            .addComponent(Password))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(username)
                            .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContentPanelLayout.createSequentialGroup()
                        .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rememberme)
                            .addGroup(ContentPanelLayout.createSequentialGroup()
                                .addComponent(loginbutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(register)))
                        .addGap(38, 38, 38)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        ContentPanelLayout.setVerticalGroup(
            ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentPanelLayout.createSequentialGroup()
                .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Username)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Password)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rememberme)
                .addGap(7, 7, 7)
                .addGroup(ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginbutton)
                    .addComponent(register))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        copyright.setText("All Rights Reserved WADDC");

        errormessage.setForeground(new java.awt.Color(-65536,true));

        javax.swing.GroupLayout ContainerPanelLayout = new javax.swing.GroupLayout(ContainerPanel);
        ContainerPanel.setLayout(ContainerPanelLayout);
        ContainerPanelLayout.setHorizontalGroup(
            ContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContainerPanelLayout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addComponent(ContentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
            .addGroup(ContainerPanelLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(copyright)
                .addContainerGap(120, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContainerPanelLayout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addGroup(ContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(errormessage, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LockLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95))
        );
        ContainerPanelLayout.setVerticalGroup(
            ContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContainerPanelLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(LockLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errormessage, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ContentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(copyright)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ContainerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ContainerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-398)/2, (screenSize.height-328)/2, 398, 328);
    }// </editor-fold>//GEN-END:initComponents

        
    private void loginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbuttonActionPerformed
        webservice ws = new webservice();
        String un=username.getText();
        String pw=password.getText();
        String pass="";
        boolean bool=false;
        
        ArrayList<String> array = new ArrayList<String>();
        
        String json_status="";
        String json_message="";
        String userid="";
        String accounttype="";
        String computerid="";
        String sid="";
        
        pass=md5hashing.getMD5(pw);
        
        array=ws.getchild_user(un, pw); 
        json_status=array.get(0); 
        json_message=array.get(1);
        userid=array.get(2);
        accounttype=array.get(3);
        
        if("success".equals(json_status) && "Child".equals(accounttype))
        {
            ArrayList<String> child = new ArrayList<String>();
            child=ws.getchildinfo(userid);
            computerid=child.get(0);
            sid=child.get(1);
            
            errormessage.setText("");
            //HideFile hide = new HideFile();
            Hidden hidden = new Hidden();
            
            hidden.setHiddenData(userid, "C://ProgramData/user.txt");
                //if 
            if("".equals(sid))
            {
               new prompt_user().setVisible(true);
               this.dispose();
            }
            else
            {
               new LockUI().setVisible(true);
               this.dispose();
            }
        }
        else if("Parent".equals(accounttype))
        {
            errormessage.setText("Account entered is a Parent!");
        }
        else if("failed".equals(json_status))
        {
            errormessage.setText("Account not found!");
        }
        /*
        Model db=new Model();
        
        db.checkaccount(un,pass); //Checks if child account in database
        bool=db.bool;
        
        if(bool==true)
        {
            //account valid
            array=db.getchild_user(un, pass);
            userid=array.get(0);
            accounttype=array.get(1);
            
            ArrayList<String> child = new ArrayList<String>();
            child=db.getchildinfo(userid);
            computerid=child.get(1);
            
            ArrayList<String> pc = new ArrayList<String>();
            
            pc=db.get_computer(computerid);
            sid=pc.get(2);
            if("Child".equals(accounttype))
            {
                errormessage.setText("");
                //System.out.print("User ID: "+userid+" Account Type: "+accounttype+"");
                HideFile hide = new HideFile();
                
                hide.hideUserid(userid);
                //if 
                if("".equals(sid))
                {
                    new prompt_user().setVisible(true);
                    this.dispose();
                }
                else{
                    new LockUI().setVisible(true);
                    this.dispose();
                }
            }
            else if("Parent".equals(accounttype))
            {
                errormessage.setText("Account entered is a Parent!");
                username.setText("");
                password.setText("");
            }
        }
        else if(bool==false)
        {
            //account invalid
            errormessage.setText("Account not found!");
            username.setText("");
            password.setText("");
        }
        */
    }//GEN-LAST:event_loginbuttonActionPerformed

    private void remembermeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remembermeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_remembermeActionPerformed

    private void registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseClicked
        // Register
        System.out.print("Hello World!");
    }//GEN-LAST:event_registerMouseClicked

    private void registerPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_registerPropertyChange
        //none
    }//GEN-LAST:event_registerPropertyChange

    private void registerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMousePressed
        new RegisterUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_registerMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                
                new LoginUI().setVisible(true);
            }

        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContainerPanel;
    private javax.swing.JPanel ContentPanel;
    private javax.swing.JLabel LockLogo;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel Username;
    private javax.swing.JLabel copyright;
    public javax.swing.JLabel errormessage;
    private javax.swing.JButton loginbutton;
    private javax.swing.JTextField password;
    private javax.swing.JLabel register;
    private javax.swing.JCheckBox rememberme;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
    
}
